version: "3"
services:
  react_frontend:
    image: react-front
    container_name: react_frontend
    build:
      context: .
      dockerfile: dockerfile-react
    ports:
      - "3000:3000"
    # volumes:
    #   - ./client:/usr/src/app
  node_backend:
    image: node-back
    container_name: node_backend
    build:
      context: .
      dockerfile: dockerfile-node
    restart: always
    ports:
      - "5000:5000"
    # volumes:
    #   - ./server:/usr/src/app
    tty: true
